#! /usr/bin/env bash

export NATS_URL=nats://localhost:4222
export ELASTICSEARCH_URI=http://localhost:9200
export ELASTICSEARCH_INDEX_NAME=jwa_item_store

set -euo pipefail

declare -a tags=(
    $(git rev-parse --verify HEAD --short)
    $(node -p -e "require('./package.json').version")
)

declare name=$(node -p -e "require('./package.json').name")

function start() {
    node dist/index.js
}

function dev() {
    npm run dev
}

function build() {
    npm run build
}

function docker-build() {
    docker build . -t jwalab/$name
}

function docker-tag() {
    for tag in ${tags[@]}
    do
        docker tag jwalab/$name jwalab/$name:$tag
    done
}

function docker-push() {
    docker push jwalab/$name
    for tag in ${tags[@]}
    do
        docker push jwalab/$name:$tag
    done
}

"$@"