version: 2.1
orbs:
    node: circleci/node@4.7.0
jobs:
    lint:
        executor:
            name: node/default
            tag: "16.6"
        steps:
            - checkout
            - run: npm install
            - run: npm run lint
    test:
        machine:
            image: ubuntu-2004:202107-02
        steps:
            - checkout
            - run: npm ci
            - run: npx minilab start
            - run:
                  command: docker-compose up
                  background: true
            # wait for elasticsearch to be up
            - run: sleep 180
            - run: ./run build
            - run:
                  command: ./run start
                  background: true
            - run: npm run test
    docker-push:
        machine: true
        steps:
            - checkout
            - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_KEY
            - run: ./run docker-build
            - run: ./run docker-tag
            - run: ./run docker-push
workflows:
    ci-cd:
        jobs:
            - lint
            - test
            - docker-push:
                  requires:
                      - lint
                      - test
                  filters:
                      branches:
                          only:
                              - main
