version: 2.1
orbs:
    node: circleci/node@4.1.1
jobs:
    lint:
        executor: node/default
        steps:
            - checkout
            - run: npm install
            - run: npm run lint
    test:
        machine:
            image: ubuntu-2004:202010-01
        steps:
            - checkout
            - run: npm install
            - run: npx minilab start
            - run:
                command: docker-compose up
                background: true
            # wait for elasticsearch to be up
            - run: sleep 180
            - run: ./run build
            - run:
                command: ./run start
                background: true
            - run: npm run test
workflows:
    tests:
        jobs:
            - lint
            - test
